language: node_js
node_js:
  - 7
notifications:
  email: false
sudo: false
before_install:
  - 'npm config set registry http://registry.npmjs.org/'
install:
  npm install
before_script:
  npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: front/www
  on:
    branch: master